# Generated by Django 6.0.1 on 2026-01-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='market_type',
            field=models.JSONField(default=list),
        ),
    ]
