# Generated by Django 6.0.1 on 2026-01-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_market_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='market_type',
            new_name='platform_type',
        ),
    ]
