# Generated by Django 6.0.1 on 2026-01-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_market_type_category_platform_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorykeyword',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categorykeyword',
            name='platform',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='categorykeyword',
            unique_together={('category', 'keyword', 'platform')},
        ),
    ]
