# Generated by Django 6.0.1 on 2026-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_categorykeyword_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorykeyword',
            options={'ordering': ['category', 'order', 'keyword']},
        ),
        migrations.AddField(
            model_name='categorykeyword',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
