# Generated by Django 6.0.3 on 2026-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_categorykeyword_options_categorykeyword_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypincode',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorypincode',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorypincode',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
