# Generated by Django 6.0.3 on 2026-07-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_categorypincode_address_categorypincode_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypincode',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
