# Generated by Django 6.0.3 on 2026-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_categorypincode_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypincode',
            name='pincode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
