# Generated by Django 4.2.23 on 2025-12-23 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('KEYWORD_SYNC', 'KEYWORD_SYNC'), ('JSON_BUILD', 'JSON_BUILD')], max_length=50)),
                ('trigger_type', models.CharField(choices=[('CRON', 'Cron'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('cron_expression', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler',
            },
        ),
        migrations.CreateModel(
            name='SchedulerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('triggered_by', models.CharField(choices=[('SYSTEM', 'System'), ('ADMIN', 'Admin')], default='SYSTEM', max_length=20)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('KEYWORD', 'Keyword'), ('BRAND', 'Brand'), ('JSON', 'JSON')], default='GLOBAL', max_length=20)),
                ('scope_id', models.BigIntegerField(blank=True, null=True)),
                ('task_group', models.CharField(choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'JSON Build'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scheduler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='scheduler.scheduler')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler_job',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('task_type', models.CharField(choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'JSON Build')], max_length=20)),
                ('entity_type', models.CharField(choices=[('KEYWORD', 'Keyword'), ('BRAND', 'Brand'), ('JSON_FILE', 'JSON File')], max_length=20)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('extra_context', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('retry_of_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.task')),
                ('scheduler_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduler.schedulerjob')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler_task',
            },
        ),
        migrations.CreateModel(
            name='BrandJsonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('filename', models.CharField(blank=True, max_length=1024, null=True)),
                ('file_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_files', to='brand.brand')),
                ('template', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brand_json_file',
                'unique_together': {('brand', 'template')},
            },
        ),
    ]
