# Generated by Django 6.0.1 on 2026-01-29 05:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0003_remove_brand_brand_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickCommerceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('product_uid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('platform', models.CharField(max_length=255, null=True)),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('pincode', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('availability', models.CharField(max_length=100)),
                ('detail_page_images', models.TextField(null=True)),
                ('msrp', models.FloatField(null=True)),
                ('sell_price', models.FloatField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('reviews', models.IntegerField(null=True)),
                ('product_url', models.URLField(max_length=1000)),
                ('thumbnail', models.URLField(max_length=1000)),
                ('main_image', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qc_products',
            },
        ),
        migrations.CreateModel(
            name='QuickCommerceSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField()),
                ('keyword', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('platform', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField(null=True)),
                ('response_time', models.DateTimeField(null=True)),
                ('process_time', models.FloatField()),
                ('status_code', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('response_file', models.CharField(max_length=500)),
                ('response_file_size', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qc_search',
            },
        ),
        migrations.CreateModel(
            name='QuickCommerceProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, null=True)),
                ('sold_by', models.CharField(max_length=255, null=True)),
                ('shipped_by', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('bullets', models.JSONField(default=list)),
                ('image_count', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='scheduler.quickcommerceproduct')),
            ],
            options={
                'db_table': 'qc_product_detail',
            },
        ),
        migrations.AddField(
            model_name='quickcommerceproduct',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scheduler.quickcommercesearch'),
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'JSON Build')], max_length=50)),
                ('trigger_type', models.CharField(choices=[('MANUAL', 'Manual'), ('CRON', 'Cron')], default='MANUAL', max_length=50)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron expression for scheduled jobs', max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler',
            },
        ),
        migrations.CreateModel(
            name='SchedulerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('triggered_by', models.CharField(choices=[('SYSTEM', 'System'), ('ADMIN', 'Admin')], default='SYSTEM', max_length=20)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('KEYWORD', 'Keyword'), ('PINCODE', 'Pincode'), ('BRAND', 'Brand'), ('JSON', 'JSON')], default='GLOBAL', max_length=20)),
                ('scope_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_group', models.CharField(choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'JSON Build')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial'), ('STOPPED', 'Stopped')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scheduler', models.ForeignKey(blank=True, help_text='Scheduler that triggered this job (null for manual runs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scheduler.scheduler')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler_job',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('task_type', models.CharField(choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'JSON Build')], max_length=20)),
                ('entity_type', models.CharField(choices=[('KEYWORD_PINCODE', 'Keyword Pincode'), ('BRAND', 'Brand'), ('JSON_FILE', 'JSON File')], max_length=20)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('extra_context', models.JSONField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('retry_of_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.task')),
                ('scheduler_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduler.schedulerjob')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler_task',
            },
        ),
        migrations.CreateModel(
            name='KeywordPincode',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('keyword', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=32)),
                ('at_synced_with_xbyte', models.DateTimeField(blank=True, null=True)),
                ('synced_with_xbyte', models.BooleanField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_completed_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_keywords', to='scheduler.task')),
                ('last_running_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_keywords', to='scheduler.task')),
            ],
            options={
                'db_table': 'keyword_pincode',
                'ordering': ('keyword', 'pincode'),
            },
        ),
        migrations.CreateModel(
            name='BrandJsonTask',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_json_task', to='brand.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_completed_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_brand_files', to='scheduler.task')),
                ('last_running_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_brand_files', to='scheduler.task')),
            ],
            options={
                'db_table': 'brand_json_task',
            },
        ),
        migrations.CreateModel(
            name='BrandJsonFile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.CharField(max_length=255)),
                ('filename', models.CharField(blank=True, max_length=1024, null=True)),
                ('file_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.DateTimeField(blank=True, null=True)),
                ('last_completed_time', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_files', to='brand.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brand_json_file',
                'unique_together': {('brand', 'template')},
            },
        ),
        migrations.AddIndex(
            model_name='quickcommerceproduct',
            index=models.Index(fields=['product_uid'], name='qc_products_product_a2484d_idx'),
        ),
        migrations.AddIndex(
            model_name='quickcommerceproduct',
            index=models.Index(fields=['title'], name='qc_products_title_e74f59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keywordpincode',
            unique_together={('keyword', 'pincode')},
        ),
        migrations.AlterUniqueTogether(
            name='brandjsontask',
            unique_together={('brand',)},
        ),
    ]
