# Generated by Django 6.0.1 on 2026-01-29 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_brand_brand_type'),
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandjsontask',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='brandjsonfile',
            name='last_run_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='brandjsontask',
            constraint=models.UniqueConstraint(fields=('brand',), name='unique_brand_json_task'),
        ),
    ]
