# Generated by Django 6.0.1 on 2026-01-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_brandjsontask_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcommerceproductdetail',
            name='document_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickcommerceproductdetail',
            name='manufacturer_part',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickcommerceproductdetail',
            name='product_view_360',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickcommerceproductdetail',
            name='run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickcommerceproductdetail',
            name='upc_retailer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproductdetail',
            name='bullets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='quickcommerceproductdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproductdetail',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproductdetail',
            name='shipped_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproductdetail',
            name='sold_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
