# Generated by Django 6.0.1 on 2026-01-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_quickcommerceproductdetail_document_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='main_image',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='msrp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='product_url',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='reviews',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='sell_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='thumbnail',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quickcommerceproductdetail',
            name='run_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
