# Generated by Django 6.0.3 on 2026-07-06 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_quickcommerceproduct_main_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcommerceproduct',
            name='brand_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quickcommerceproduct',
            name='brand_review_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quickcommerceproduct',
            name='brand_reviews',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='keywordpincode',
            index=models.Index(fields=['keyword', 'pincode'], name='keyword_pin_keyword_0a7cf3_idx'),
        ),
    ]
