# Generated by Django 6.0.3 on 2026-07-09 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_quickcommerceproduct_brand_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quickcommerceproduct',
            index=models.Index(fields=['keyword', 'pincode', 'platform'], name='qc_products_keyword_738b30_idx'),
        ),
        migrations.AddIndex(
            model_name='quickcommerceproduct',
            index=models.Index(fields=['brand'], name='qc_products_brand_ba2118_idx'),
        ),
        migrations.AddIndex(
            model_name='quickcommercesearch',
            index=models.Index(fields=['task_id'], name='qc_search_task_id_e50e76_idx'),
        ),
        migrations.AddIndex(
            model_name='quickcommercesearch',
            index=models.Index(fields=['keyword', 'pincode', 'platform'], name='qc_search_keyword_51c716_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='scheduler_t_status_88b119_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='scheduler_t_task_ty_268ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['entity_type', 'entity_id'], name='scheduler_t_entity__f696c1_idx'),
        ),
    ]
