# Generated by Django 6.0.3 on 2026-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_quickcommerceproduct_qc_products_keyword_738b30_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordpincode',
            name='pincode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quickcommercesearch',
            name='pincode',
            field=models.CharField(max_length=255),
        ),
    ]
