# Generated by Django 6.0.3 on 2026-07-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_keywordpincode_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='main_image',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='product_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quickcommerceproduct',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
