# Generated by Django 6.0.3 on 2026-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
