# Generated by Django 6.0.3 on 2026-07-15 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. openai, gemini, anthropic', max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, help_text='e.g. gpt-4o, gemini-2.5-flash', max_length=100, null=True)),
            ],
            options={
                'db_table': 'llm_providers',
                'ordering': ('name',),
            },
        ),
    ]
