# Generated by Django 6.0.3 on 2026-07-22 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. openai, gemini, anthropic', max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False, help_text='Fallback provider if none specified')),
                ('api_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('model', models.CharField(blank=True, help_text='e.g. gpt-4o, gemini-2.5-flash', max_length=100, null=True)),
                ('base_url', models.CharField(blank=True, help_text='e.g. custom proxy URL', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timeout_seconds', models.IntegerField(default=60)),
                ('max_retries', models.IntegerField(default=3)),
                ('health_check_path', models.CharField(blank=True, help_text="Path to check API health (e.g., '/v1/models')", max_length=255)),
                ('health_check_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'llm_providers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='core_llm_providers.llmprovider')),
            ],
            options={
                'db_table': 'token_usage_logs',
                'indexes': [models.Index(fields=['timestamp'], name='token_usage_timesta_48a052_idx'), models.Index(fields=['brand_id', 'timestamp'], name='token_usage_brand_i_d8132c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageSummary',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('requests', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to='core_llm_providers.llmprovider')),
            ],
            options={
                'db_table': 'token_usage_summaries',
                'indexes': [models.Index(fields=['date'], name='token_usage_date_ca8948_idx'), models.Index(fields=['brand_id', 'date'], name='token_usage_brand_i_dfdde2_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'provider', 'type', 'brand_id'), name='unique_token_summary_dimension')],
            },
        ),
    ]
