# Generated by Django 6.0.3 on 2026-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_llm_providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='base_url',
            field=models.CharField(blank=True, help_text='e.g. custom proxy URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='timeout_seconds',
            field=models.IntegerField(default=60),
        ),
    ]
