# Generated by Django 6.0.3 on 2026-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_llm_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='base_url',
            field=models.CharField(blank=True, default='', help_text='e.g. custom proxy URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='health_check_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='model',
            field=models.CharField(blank=True, default='', help_text='e.g. gpt-4o, gemini-2.5-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='tokenusagelog',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenusagelog',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tokenusagesummary',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenusagesummary',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
