# Generated by Django 6.0.3 on 2026-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_llm_providers', '0002_llmprovider_base_url_llmprovider_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='health_check_path',
            field=models.CharField(blank=True, help_text="Path to check API health (e.g., '/v1/models')", max_length=255),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='health_check_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
