# Generated by Django 6.0.3 on 2026-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_llm_providers', '0002_alter_llmprovider_api_key_alter_llmprovider_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique internal identifier (e.g. OPENAI, GEMINI)', max_length=50),
        ),
    ]
