# Generated by Django 6.0.3 on 2026-07-21 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_llm_providers', '0003_llmprovider_health_check_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Fallback provider if none specified'),
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='core_llm_providers.llmprovider')),
            ],
            options={
                'db_table': 'token_usage_logs',
                'indexes': [models.Index(fields=['timestamp'], name='token_usage_timesta_48a052_idx'), models.Index(fields=['brand_id', 'timestamp'], name='token_usage_brand_i_d8132c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageSummary',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('requests', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to='core_llm_providers.llmprovider')),
            ],
            options={
                'db_table': 'token_usage_summaries',
                'indexes': [models.Index(fields=['date'], name='token_usage_date_ca8948_idx'), models.Index(fields=['brand_id', 'date'], name='token_usage_brand_i_dfdde2_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'provider', 'type', 'brand_id'), name='unique_token_summary_dimension')],
            },
        ),
    ]
