# Generated by Django 6.0.3 on 2026-07-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_llm_providers', '0004_llmprovider_is_default_tokenusagelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='api_key',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
