# Generated by Django 6.0.3 on 2026-07-14 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'TokenUsageLogs',
                'indexes': [models.Index(fields=['timestamp'], name='TokenUsageL_timesta_e51a04_idx'), models.Index(fields=['brand_id', 'timestamp'], name='TokenUsageL_brand_i_b7edb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageSummary',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('provider', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('requests', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'TokenUsageSummaries',
                'indexes': [models.Index(fields=['date'], name='TokenUsageS_date_ec75d8_idx'), models.Index(fields=['brand_id', 'date'], name='TokenUsageS_brand_i_8d3362_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'provider', 'type', 'brand_id'), name='unique_token_summary_dimension')],
            },
        ),
    ]
