# Generated by Django 6.0.3 on 2026-07-14 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_organizations', '0001_initial'),
        ('experience_cloud_executions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTemplate',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255, unique=True)),
                ('process_type', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=50, null=True)),
                ('format', models.CharField(blank=True, choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'json_templates',
            },
        ),
        migrations.CreateModel(
            name='RegionJsonFile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('file_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('generation_duration', models.FloatField(blank=True, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_organizations.region')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_files', to='experience_cloud_executions.jsonfiletask')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_json_generator.jsontemplate')),
            ],
            options={
                'db_table': 'region_json_files',
            },
        ),
    ]
