# Generated by Django 6.0.3 on 2026-09-01 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTemplate',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('parent_folder', models.CharField(blank=True, choices=[('experience-cloud', 'Experience Cloud'), ('media-cloud', 'Media Cloud'), ('identity-cloud', 'Identity Cloud')], default='', max_length=255)),
                ('process_type', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='', max_length=50)),
                ('file_format', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='experience_cloud_json_generator.jsontemplate')),
            ],
            options={
                'db_table': 'json_templates',
            },
        ),
        migrations.CreateModel(
            name='RegionJsonFile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=1024)),
                ('file_path', models.CharField(blank=True, default='', max_length=2048)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=255)),
                ('generation_duration', models.FloatField(blank=True, null=True)),
                ('products_processed', models.IntegerField(blank=True, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_organizations.region')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_json_generator.jsontemplate')),
            ],
            options={
                'db_table': 'region_json_files',
            },
        ),
    ]
