# Generated by Django 6.0.3 on 2026-07-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_json_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionjsonfile',
            name='products_processed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
