# Generated by Django 6.0.3 on 2026-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_json_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsontemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
