# Generated by Django 6.0.3 on 2026-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_json_generator', '0002_regionjsonfile_products_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsontemplate',
            name='format',
            field=models.CharField(blank=True, choices=[('csv', 'CSV'), ('json', 'JSON')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jsontemplate',
            name='process_type',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='regionjsonfile',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='regionjsonfile',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionjsonfile',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='regionjsonfile',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='regionjsonfile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='regionjsonfile',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
