# Generated by Django 6.0.3 on 2026-08-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_json_generator', '0003_alter_jsontemplate_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsontemplate',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jsontemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='experience_cloud_json_generator.jsontemplate'),
        ),
    ]
