# Generated by Django 6.0.3 on 2026-08-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_json_generator', '0004_jsontemplate_file_name_jsontemplate_parent_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsontemplate',
            name='parent_folder',
            field=models.CharField(blank=True, choices=[('experience-cloud', 'Experience Cloud'), ('media-cloud', 'Media Cloud'), ('identity-cloud', 'Identity Cloud')], default='', max_length=255),
        ),
    ]
