# Generated by Django 6.0.3 on 2026-08-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_json_generator', '0005_jsontemplate_parent_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsontemplate',
            name='format',
        ),
        migrations.AddField(
            model_name='jsontemplate',
            name='file_format',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
