# Generated by Django 6.0.3 on 2026-07-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scrapinglog',
            index=models.Index(fields=['status', 'platform'], name='scraping_lo_status_a2b4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapinglog',
            index=models.Index(fields=['created_at'], name='scraping_lo_created_2c54d0_idx'),
        ),
    ]
