# Generated by Django 6.0.3 on 2026-07-15 08:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('cron', models.CharField(blank=True, max_length=100, null=True)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedulers',
            },
        ),
        migrations.CreateModel(
            name='ActiveExecution',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('execution_type', models.CharField(blank=True, choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'Json Build')], max_length=50, null=True)),
                ('scope_type', models.CharField(blank=True, choices=[('CATEGORY', 'Category'), ('KEYWORD', 'Keyword'), ('LOCATION', 'Location'), ('REGION', 'Region')], max_length=50, null=True)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], max_length=50, null=True)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('celery_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scheduler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_executions.scheduler')),
            ],
            options={
                'db_table': 'active_executions',
            },
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('execution_type', models.CharField(blank=True, choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'Json Build')], max_length=50, null=True)),
                ('scope_type', models.CharField(blank=True, choices=[('CATEGORY', 'Category'), ('KEYWORD', 'Keyword'), ('LOCATION', 'Location'), ('REGION', 'Region')], max_length=50, null=True)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], max_length=50, null=True)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('celery_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scheduler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_executions.scheduler')),
            ],
            options={
                'db_table': 'execution_history',
            },
        ),
        migrations.CreateModel(
            name='DataDumpTask',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('api_dump_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Stores keyword, location, or region_json IDs', null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_executions.activeexecution')),
            ],
            options={
                'db_table': 'data_dump_tasks',
                'indexes': [models.Index(fields=['execution', 'status'], name='idx_datadump_exec_status')],
            },
        ),
        migrations.CreateModel(
            name='JsonFileTask',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('region_json_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Stores keyword, location, or region_json IDs', null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_executions.activeexecution')),
            ],
            options={
                'db_table': 'json_file_tasks',
                'indexes': [models.Index(fields=['execution', 'status'], name='idx_jsonfile_exec_status')],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'Json Build')], max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_metadata', models.JSONField(blank=True, help_text='Stores keyword, location, or region_json IDs', null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_tasks', to='experience_cloud_executions.executionhistory')),
            ],
            options={
                'db_table': 'task_history',
                'indexes': [models.Index(fields=['execution', 'task_type'], name='idx_taskhist_exec_type'), models.Index(fields=['celery_task_id'], name='idx_taskhist_celery_id')],
            },
        ),
    ]
