# Generated by Django 6.0.3 on 2026-07-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='concurrency_policy',
            field=models.CharField(choices=[('ALLOW', 'Allow'), ('SKIP', 'Skip'), ('REPLACE', 'Replace')], default='SKIP', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='notify_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='retry_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='retry_delay_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='timeout_seconds',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
