# Generated by Django 6.0.3 on 2026-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_executions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeexecution',
            name='celery_group_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activeexecution',
            name='execution_type',
            field=models.CharField(blank=True, choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'Json Build')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='activeexecution',
            name='scope_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activeexecution',
            name='scope_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activeexecution',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('CATEGORY', 'Category'), ('KEYWORD', 'Keyword'), ('LOCATION', 'Location'), ('REGION', 'Region')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='activeexecution',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datadumptask',
            name='api_dump_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datadumptask',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datadumptask',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='datadumptask',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='executionhistory',
            name='celery_group_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='executionhistory',
            name='execution_type',
            field=models.CharField(blank=True, choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'Json Build')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='executionhistory',
            name='scope_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='executionhistory',
            name='scope_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='executionhistory',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('CATEGORY', 'Category'), ('KEYWORD', 'Keyword'), ('LOCATION', 'Location'), ('REGION', 'Region')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='executionhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jsonfiletask',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jsonfiletask',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jsonfiletask',
            name='region_json_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jsonfiletask',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='cron',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='type',
            field=models.CharField(blank=True, choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'Json Build')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='resource_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
