# Generated by Django 6.0.3 on 2026-07-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_executions', '0002_scheduler_concurrency_policy_scheduler_notify_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='type',
            field=models.CharField(blank=True, choices=[('DATA_DUMP', 'Data Dump'), ('JSON_BUILD', 'Json Build')], max_length=50, null=True),
        ),
    ]
