# Generated by Django 6.0.3 on 2026-07-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_executions', '0003_alter_scheduler_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeexecution',
            name='scope_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='scope_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
