# Generated by Django 6.0.3 on 2026-07-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_executions', '0004_activeexecution_scope_id_executionhistory_scope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeexecution',
            name='stopped_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='stopped_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
