# Generated by Django 6.0.3 on 2026-07-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_executions', '0005_activeexecution_stopped_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeexecution',
            name='scope_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='scope_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
