# Generated by Django 5.0.3 on 2026-07-07 10:41

from django.db import migrations

def populate_platforms(apps, schema_editor):
    Platform = apps.get_model('platform', 'Platform')
    
    quick_commerce_platforms = [
        "instamart", "zepto", "blinkit", "bigbasket", "amazon_fresh", "noon_ksa"
    ]
    
    marketplace_platforms = [
        "amazon", "amazon_sa", "flipkart", "vijaysales", "reliancedigital", "croma"
    ]
    
    for value in quick_commerce_platforms:
        name = value.replace('_', ' ').title()
        Platform.objects.get_or_create(
            value=value,
            defaults={
                'name': name,
                'platform_type': 'quick_commerce',
                'status': 'active'
            }
        )
        
    for value in marketplace_platforms:
        name = value.replace('_', ' ').title()
        Platform.objects.get_or_create(
            value=value,
            defaults={
                'name': name,
                'platform_type': 'marketplace',
                'status': 'active'
            }
        )

def reverse_platforms(apps, schema_editor):
    Platform = apps.get_model('platform', 'Platform')
    Platform.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_platforms, reverse_platforms),
    ]
