# Generated by Django 6.0.3 on 2026-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_auto_20260707_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
