# Generated by Django 6.0.3 on 2026-07-22 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_categories', '0001_initial'),
        ('core_organizations', '0002_initial'),
        ('experience_cloud_api_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('platform_type', models.CharField(blank=True, max_length=100, null=True)),
                ('json_configuration', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('api_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='experience_cloud_api_provider.apiprovider')),
            ],
            options={
                'db_table': 'platforms',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_categories.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_organizations.region')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_catalog.platform')),
            ],
            options={
                'db_table': 'locations',
                'indexes': [models.Index(fields=['region', 'platform'], name='idx_location_region_platform')],
                'constraints': [models.UniqueConstraint(fields=('region', 'platform', 'category', 'pincode'), name='unique_location_combo')],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_categories.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_organizations.region')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_catalog.platform')),
            ],
            options={
                'db_table': 'keywords',
                'indexes': [models.Index(fields=['region', 'platform'], name='idx_keyword_region_platform')],
                'constraints': [models.UniqueConstraint(fields=('region', 'platform', 'category', 'keyword'), name='unique_keyword_combo')],
            },
        ),
    ]
