# Generated by Django 6.0.3 on 2026-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='value',
        ),
        migrations.AlterField(
            model_name='platform',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
