# Generated by Django 6.0.3 on 2026-07-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_catalog', '0002_remove_platform_value_alter_platform_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='json_configuration',
            new_name='configuration',
        ),
    ]
