# Generated by Django 6.0.3 on 2026-07-17 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0001_initial'),
        ('experience_cloud_catalog', '0002_remove_platform_source_platform_api_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='api_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='experience_cloud_api_provider.apiprovider'),
        ),
    ]
