# Generated by Django 6.0.3 on 2026-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_catalog', '0003_alter_platform_api_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
