# Generated by Django 6.0.3 on 2026-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_categories', '0002_alter_category_description'),
        ('core_organizations', '0004_alter_brand_aliases_alter_brand_code_and_more'),
        ('experience_cloud_catalog', '0003_rename_json_configuration_platform_configuration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_combo',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('region', 'platform', 'category', 'pincode', 'address'), name='unique_location_combo'),
        ),
    ]
