# Generated by Django 6.0.3 on 2026-07-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_catalog', '0004_remove_location_unique_location_combo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_combo',
        ),
    ]
