# Generated by Django 6.0.3 on 2026-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_categories', '0002_alter_category_description'),
        ('core_organizations', '0004_alter_brand_aliases_alter_brand_code_and_more'),
        ('experience_cloud_catalog', '0005_remove_location_unique_location_combo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('region', 'platform', 'category', 'pincode', 'address'), name='unique_location_combo'),
        ),
    ]
