# Generated by Django 6.0.3 on 2026-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XBytesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('product_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.CharField(blank=True, max_length=50, null=True)),
                ('sell_price', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('reviews', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_reviews', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_review_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_part', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('upc_retailer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=255, null=True)),
                ('shipped_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product_url', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('main_image', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('image_count', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('document_count', models.IntegerField(default=0)),
                ('product_view_360', models.BooleanField(default=False)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('run_date', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['product_uid', 'platform'], name='idx_prod_uid_platform'), models.Index(fields=['rank'], name='idx_apidump_rank'), models.Index(fields=['platform', 'keyword', 'location'], name='idx_plat_key_loc'), models.Index(fields=['created_at'], name='idx_product_created_at'), models.Index(fields=['brand'], name='idx_product_brand')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'keyword', 'location', 'product_uid'), name='unique_product_fetch')],
            },
        ),
    ]
