# Generated by Django 6.0.3 on 2026-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karmatechkeyword',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='karmatechproduct',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='karmatechproductranking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='karmatechreview',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='xbytesproduct',
            name='last_seen_batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='xbytesproduct',
            index=models.Index(fields=['last_seen_batch_id'], name='idx_prod_batch_id'),
        ),
    ]
