# Generated by Django 6.0.3 on 2026-07-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbytesproduct',
            name='document_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='image_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='product_view_360',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='video_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
