# Generated by Django 6.0.3 on 2026-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0002_alter_karmatechkeyword_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbytesproduct',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='keyword',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='manufacturer_part',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='shipped_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='sold_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesreview',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesreview',
            name='review_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
