# Generated by Django 6.0.3 on 2026-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0002_alter_xbytesproduct_document_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbytesproduct',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesproduct',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
