# Generated by Django 6.0.3 on 2026-08-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0003_alter_xbytesproduct_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBytesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.TextField(blank=True, null=True)),
                ('product_title', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('review_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewer_profile_url', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('review_title', models.TextField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_purchase', models.CharField(blank=True, max_length=50, null=True)),
                ('helpful_count', models.CharField(blank=True, max_length=50, null=True)),
                ('review_images', models.TextField(blank=True, null=True)),
                ('video_urls', models.TextField(blank=True, null=True)),
                ('variant_info', models.TextField(blank=True, null=True)),
                ('review_url', models.TextField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xbytes_reviews',
                'indexes': [models.Index(fields=['sku'], name='idx_xbytes_review_sku'), models.Index(fields=['brand'], name='idx_xbytes_review_brand'), models.Index(fields=['review_id'], name='idx_xbytes_review_id')],
            },
        ),
    ]
