# Generated by Django 6.0.3 on 2026-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0004_xbytesreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbytesreview',
            name='helpful_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesreview',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesreview',
            name='review_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesreview',
            name='reviewer_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesreview',
            name='timestamp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbytesreview',
            name='verified_purchase',
            field=models.TextField(blank=True, null=True),
        ),
    ]
