# Generated by Django 6.0.3 on 2026-08-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0005_alter_xbytesreview_helpful_count_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='xbytesreview',
            constraint=models.UniqueConstraint(fields=('sku', 'review_id'), name='unique_xbytes_review'),
        ),
    ]
