# Generated by Django 6.0.3 on 2026-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0006_xbytesreview_unique_xbytes_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='xbytesreview',
            name='unique_xbytes_review',
        ),
        migrations.AddField(
            model_name='xbytesreview',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='xbytesreview',
            constraint=models.UniqueConstraint(fields=('platform', 'sku', 'review_id'), name='unique_xbytes_review'),
        ),
    ]
