# Generated by Django 6.0.3 on 2026-08-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0007_remove_xbytesreview_unique_xbytes_review_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xbytesreview',
            table='reviews',
        ),
    ]
