# Generated by Django 6.0.3 on 2026-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='aliases',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='aliases',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
