# Generated by Django 6.0.3 on 2026-07-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_organizations', '0002_brand_created_by_brand_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='region',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='core_organizations.brand'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
