# Generated by Django 6.0.3 on 2026-07-16 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_categories', '0001_initial'),
        ('core_organizations', '0003_remove_competitor_region_brand_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_categories.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='core_organizations.region'),
        ),
    ]
