# Generated by Django 6.0.3 on 2026-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_organizations', '0004_remove_competitor_brand_brand_category_brand_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
