# Generated by Django 6.0.3 on 2026-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_organizations', '0004_alter_brand_aliases_alter_brand_code_and_more'),
        ('experience_cloud_catalog', '0006_location_unique_location_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='competitors', to='experience_cloud_catalog.platform'),
        ),
    ]
