# Generated by Django 6.0.3 on 2026-07-14 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProvider',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_url', models.CharField(blank=True, max_length=500, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('authentication', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'api_providers',
            },
        ),
    ]
