# Generated by Django 6.0.3 on 2026-07-22 13:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProvider',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique provider name', max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Unique internal identifier (e.g. STRIPE, TWILIO)', max_length=50, unique=True)),
                ('base_url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator()])),
                ('api_version', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_type', models.CharField(choices=[('NONE', 'None'), ('API_KEY', 'API Key'), ('BASIC', 'Basic Auth'), ('BEARER', 'Bearer Token'), ('OAUTH2', 'OAuth2'), ('JWT', 'JWT'), ('CUSTOM', 'Custom')], default='NONE', max_length=20)),
                ('default_headers', models.JSONField(blank=True, default=dict)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Keys/tokens. MUST BE ENCRYPTED at the application/database layer.')),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Timeout in seconds')),
                ('retry_count', models.PositiveSmallIntegerField(default=3)),
                ('retry_delay', models.PositiveSmallIntegerField(default=2, help_text='Retry delay in seconds')),
                ('health_check_path', models.CharField(blank=True, help_text="Path to check API health (e.g., '/health')", max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=20)),
                ('health_check_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_providers',
            },
        ),
        migrations.CreateModel(
            name='APIUsageSummary',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('success_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'api_usage_summaries',
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('request_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('response_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('api_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_api_provider.apiprovider')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_categories.category')),
            ],
            options={
                'db_table': 'api_usage_logs',
            },
        ),
    ]
