# Generated by Django 6.0.3 on 2026-07-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience_cloud_api_provider', '0001_initial'),
        ('experience_cloud_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.keyword'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.location'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.platform'),
        ),
        migrations.AddField(
            model_name='apiusagesummary',
            name='api_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_api_provider.apiprovider'),
        ),
        migrations.AddField(
            model_name='apiusagesummary',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_catalog.platform'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['timestamp'], name='api_usage_l_timesta_5a0769_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['brand_id', 'timestamp'], name='api_usage_l_brand_i_e72dec_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['api_provider', 'status'], name='api_usage_l_api_pro_c00445_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagesummary',
            index=models.Index(fields=['date'], name='api_usage_s_date_9f3a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagesummary',
            index=models.Index(fields=['brand_id', 'date'], name='api_usage_s_brand_i_f2b957_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiusagesummary',
            constraint=models.UniqueConstraint(fields=('date', 'api_provider', 'platform', 'brand_id', 'region_id'), name='unique_api_summary_dimension'),
        ),
    ]
