# Generated by Django 6.0.3 on 2026-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='timeout_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
