# Generated by Django 6.0.3 on 2026-07-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiprovider',
            name='test_http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', help_text='HTTP method used for health checks and connection testing', max_length=10),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='test_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Payload sent during health checks (for POST/PUT/PATCH)'),
        ),
    ]
