# Generated by Django 6.0.3 on 2026-07-17 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0002_apiprovider_description_apiprovider_max_retries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiprovider',
            name='authentication',
        ),
        migrations.RemoveField(
            model_name='apiprovider',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='apiprovider',
            name='max_retries',
        ),
        migrations.RemoveField(
            model_name='apiprovider',
            name='timeout_seconds',
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='api_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='auth_type',
            field=models.CharField(choices=[('NONE', 'None'), ('API_KEY', 'API Key'), ('BASIC', 'Basic Auth'), ('BEARER', 'Bearer Token'), ('OAUTH2', 'OAuth2'), ('JWT', 'JWT'), ('CUSTOM', 'Custom')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='code',
            field=models.CharField(db_index=True, default='temp', help_text='Unique internal identifier (e.g. STRIPE, TWILIO)', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Keys/tokens. MUST BE ENCRYPTED at the application/database layer.'),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='default_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='health_check_path',
            field=models.CharField(blank=True, help_text="Path to check API health (e.g., '/health')", max_length=255),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='health_check_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='retry_delay',
            field=models.PositiveSmallIntegerField(default=2, help_text='Retry delay in seconds'),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='timeout',
            field=models.PositiveIntegerField(default=30, help_text='Timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='apiprovider',
            name='base_url',
            field=models.URLField(default='temp', max_length=500, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiprovider',
            name='name',
            field=models.CharField(db_index=True, default='temp', help_text='Unique provider name', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiprovider',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=20),
        ),
    ]
