# Generated by Django 6.0.3 on 2026-07-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0003_apiprovider_test_http_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
