# Generated by Django 6.0.3 on 2026-07-22 05:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_categories', '0001_initial'),
        ('experience_cloud_api_provider', '0003_remove_apiprovider_authentication_and_more'),
        ('experience_cloud_catalog', '0004_keyword_is_active_location_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('request_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('response_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('api_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_api_provider.apiprovider')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_categories.category')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.keyword')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.location')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.platform')),
            ],
            options={
                'db_table': 'api_usage_logs',
                'indexes': [models.Index(fields=['timestamp'], name='api_usage_l_timesta_5a0769_idx'), models.Index(fields=['brand_id', 'timestamp'], name='api_usage_l_brand_i_e72dec_idx'), models.Index(fields=['api_provider', 'status'], name='api_usage_l_api_pro_c00445_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsageSummary',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('success_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('api_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_api_provider.apiprovider')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='experience_cloud_catalog.platform')),
            ],
            options={
                'db_table': 'api_usage_summaries',
                'indexes': [models.Index(fields=['date'], name='api_usage_s_date_9f3a0e_idx'), models.Index(fields=['brand_id', 'date'], name='api_usage_s_brand_i_f2b957_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'api_provider', 'platform', 'brand_id', 'region_id'), name='unique_api_summary_dimension')],
            },
        ),
    ]
