# Generated by Django 6.0.3 on 2026-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0004_apiusagelog_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiprovider',
            name='api_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='apiprovider',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apiprovider',
            name='health_check_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apiusagesummary',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
