# Generated by Django 6.0.3 on 2026-07-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0005_alter_apiprovider_api_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusagelog',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='apiusagelog',
            name='location',
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='keyword_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
