# Generated by Django 6.0.3 on 2026-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0006_remove_apiusagelog_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apiusagelog',
            name='api_usage_l_brand_i_e72dec_idx',
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='brand_ids',
            field=models.TextField(blank=True, default='', help_text='Comma-separated brand IDs'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='brand_names',
            field=models.TextField(blank=True, default='', help_text='Comma-separated brand names'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='region_ids',
            field=models.TextField(blank=True, default='', help_text='Comma-separated region IDs'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='region_names',
            field=models.TextField(blank=True, default='', help_text='Comma-separated region names'),
        ),
        migrations.RemoveField(
            model_name='apiusagelog',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='apiusagelog',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='apiusagelog',
            name='region_id',
        ),
    ]
