# Generated by Django 6.0.3 on 2026-07-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0007_remove_apiusagelog_api_usage_l_brand_i_e72dec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagesummary',
            name='region_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
