# Generated by Django 6.0.3 on 2026-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('ORGANIZATION', 'Organization')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('ORGANIZATION', 'Organization')], default='', max_length=50),
        ),
    ]
