# Generated by Django 6.0.3 on 2026-08-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_organizations', '0004_alter_brand_aliases_alter_brand_code_and_more'),
        ('core_users', '0002_alter_role_code_alter_role_role_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='users', to='core_organizations.brand'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='users', to='core_organizations.region'),
        ),
    ]
