# Generated by Django 6.0.3 on 2026-07-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_users', '0002_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
