# Generated by Django 6.0.3 on 2026-07-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_users', '0003_user_extra_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
