# Generated by Django 6.0.3 on 2026-07-15 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience_cloud_api_provider', '0001_initial'),
        ('experience_cloud_catalog', '0001_initial'),
        ('experience_cloud_executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('product_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.CharField(blank=True, max_length=50, null=True)),
                ('sell_price', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('reviews', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_reviews', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_review_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_part', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('upc_retailer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=255, null=True)),
                ('shipped_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product_url', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('main_image', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('image_count', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('document_count', models.IntegerField(default=0)),
                ('product_view_360', models.BooleanField(default=False)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('run_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['product_uid', 'platform'], name='idx_prod_uid_platform'), models.Index(fields=['rank'], name='idx_apidump_rank'), models.Index(fields=['platform', 'keyword', 'location'], name='idx_plat_key_loc'), models.Index(fields=['created_at'], name='idx_product_created_at'), models.Index(fields=['brand'], name='idx_product_brand')],
            },
        ),
        migrations.CreateModel(
            name='ApiDump',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_count', models.IntegerField(default=0)),
                ('products_found', models.IntegerField(default=0)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('api_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_api_provider.apiprovider')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.keyword')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.location')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.platform')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_executions.datadumptask')),
            ],
            options={
                'db_table': 'api_dumps',
                'indexes': [models.Index(fields=['keyword', 'location', 'created_at'], name='idx_api_dump_lookup')],
            },
        ),
    ]
