# Generated by Django 6.0.3 on 2026-07-22 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience_cloud_api_provider', '0001_initial'),
        ('experience_cloud_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDump',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_count', models.IntegerField(default=0)),
                ('products_found', models.IntegerField(default=0)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('api_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_api_provider.apiprovider')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.keyword')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.location')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.platform')),
            ],
            options={
                'db_table': 'api_dumps',
                'indexes': [models.Index(fields=['keyword', 'location', 'created_at'], name='idx_api_dump_lookup')],
            },
        ),
    ]
