# Generated by Django 6.0.3 on 2026-09-01 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience_cloud_api_provider', '0001_initial'),
        ('experience_cloud_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportJob',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('REVIEWS', 'Reviews'), ('DATA_DUMP', 'Data Dump')], default='REVIEWS', max_length=50)),
                ('platform', models.CharField(blank=True, default='', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('file_size_bytes', models.BigIntegerField(default=0, help_text='Total file size uploaded in bytes')),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PENDING_PROCESSING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADING', max_length=50)),
                ('upload_id', models.CharField(blank=True, default='', max_length=255)),
                ('upload_started_at', models.DateTimeField(blank=True, null=True)),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True)),
                ('upload_duration', models.FloatField(blank=True, help_text='Time taken to upload the file (seconds)', null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.FloatField(blank=True, help_text='Time taken to process the file (seconds)', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'data_import_jobs',
                'indexes': [models.Index(fields=['status'], name='idx_data_import_status'), models.Index(fields=['import_type'], name='idx_data_import_type')],
            },
        ),
        migrations.CreateModel(
            name='ApiDump',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('product_count', models.IntegerField(default=0)),
                ('products_found', models.IntegerField(default=0)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('region_ids', models.JSONField(default=list)),
                ('region_names', models.JSONField(default=list)),
                ('api_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_api_provider.apiprovider')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_cloud_catalog.platform')),
            ],
            options={
                'db_table': 'api_dumps',
                'indexes': [models.Index(fields=['keyword_name', 'location_name', 'created_at'], name='idx_api_dump_lookup')],
            },
        ),
    ]
