# Generated by Django 6.0.3 on 2026-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_market_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidump',
            name='task',
        ),
        migrations.AddField(
            model_name='apidump',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apidump',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
