# Generated by Django 6.0.3 on 2026-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportjob',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Groups multiple files together', max_length=100, null=True),
        ),
    ]
