# Generated by Django 6.0.3 on 2026-07-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_api_provider', '0006_remove_apiusagelog_keyword_and_more'),
        ('experience_cloud_catalog', '0005_remove_location_unique_location_combo'),
        ('experience_cloud_market_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apidump',
            name='idx_api_dump_lookup',
        ),
        migrations.AddField(
            model_name='apidump',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apidump',
            name='keyword_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apidump',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apidump',
            name='region_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='apidump',
            name='region_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='apidump',
            index=models.Index(fields=['keyword_name', 'location_name', 'created_at'], name='idx_api_dump_lookup'),
        ),
        migrations.RemoveField(
            model_name='apidump',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='apidump',
            name='location',
        ),
    ]
