# Generated by Django 6.0.3 on 2026-07-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_market_data', '0002_remove_apidump_task_apidump_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_prod_uid_platform',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_apidump_rank',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_plat_key_loc',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_created_at',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_brand',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
