# Generated by Django 6.0.3 on 2026-08-31 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_market_data', '0002_remove_apidump_idx_api_dump_lookup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportJob',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('REVIEWS', 'Reviews'), ('DATA_DUMP', 'Data Dump')], default='REVIEWS', max_length=50)),
                ('platform', models.CharField(blank=True, default='', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PENDING_PROCESSING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADING', max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('upload_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'data_import_jobs',
                'indexes': [models.Index(fields=['status'], name='idx_data_import_status'), models.Index(fields=['import_type'], name='idx_data_import_type')],
            },
        ),
    ]
