# Generated by Django 6.0.3 on 2026-09-18 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_market_data', '0002_dataimportjob_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimportjob',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='dataimportjob',
            name='file',
        ),
        migrations.RemoveField(
            model_name='dataimportjob',
            name='file_size_bytes',
        ),
        migrations.RemoveField(
            model_name='dataimportjob',
            name='last_processed_at',
        ),
        migrations.RemoveField(
            model_name='dataimportjob',
            name='upload_completed_at',
        ),
        migrations.RemoveField(
            model_name='dataimportjob',
            name='upload_duration',
        ),
        migrations.RemoveField(
            model_name='dataimportjob',
            name='upload_id',
        ),
        migrations.RemoveField(
            model_name='dataimportjob',
            name='upload_started_at',
        ),
        migrations.AlterField(
            model_name='dataimportjob',
            name='processing_duration',
            field=models.FloatField(blank=True, help_text='Total time taken for the entire batch (seconds)', null=True),
        ),
        migrations.CreateModel(
            name='DataImportFile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('file_size_bytes', models.BigIntegerField(default=0, help_text='Total file size uploaded in bytes')),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PENDING_PROCESSING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADING', max_length=50)),
                ('upload_id', models.CharField(blank=True, default='', max_length=255)),
                ('upload_started_at', models.DateTimeField(blank=True, null=True)),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True)),
                ('upload_duration', models.FloatField(blank=True, help_text='Time taken to upload the file (seconds)', null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.FloatField(blank=True, help_text='Time taken to process the file (seconds)', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='experience_cloud_market_data.dataimportjob')),
            ],
            options={
                'db_table': 'data_import_files',
                'indexes': [models.Index(fields=['status'], name='idx_data_import_file_status')],
            },
        ),
    ]
