# Generated by Django 6.0.3 on 2026-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_market_data', '0003_dataimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportjob',
            name='failed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0, help_text='Total file size uploaded in bytes'),
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='processing_duration',
            field=models.FloatField(blank=True, help_text='Time taken to process the file (seconds)', null=True),
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='upload_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='upload_duration',
            field=models.FloatField(blank=True, help_text='Time taken to upload the file (seconds)', null=True),
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='upload_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
