# Generated by Django 6.0.3 on 2026-09-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_market_data', '0003_remove_dataimportjob_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportjob',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Frontend UUID to group this session', max_length=100, null=True, unique=True),
        ),
    ]
