# Generated by Django 6.0.3 on 2026-09-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience_cloud_market_data', '0004_dataimportjob_batch_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimportfile',
            options={'ordering': ['file']},
        ),
    ]
