# Generated by Django 6.0.1 on 2026-01-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_type',
        ),
    ]
