# Generated by Django 4.2.23 on 2025-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brand_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('marketplace', 'Marketplace'), ('quick_commerce', 'Quick Commerce')], default='marketplace', max_length=20),
        ),
    ]
